In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv('Данные для тестового задания - Данные об аудитории.csv')

In [36]:
df.dtypes

date            object
user_id         object
view_adverts     int64
dtype: object

In [37]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date            datetime64[ns]
user_id                 object
view_adverts             int64
dtype: object

In [38]:
df["date"] = pd.to_datetime(df["date"])

mau = df[(df["date"].dt.month == 11)]["user_id"].nunique()

print(mau)

7639

In [39]:
df["date"] = pd.to_datetime(df["date"])

dau = df.groupby(df["date"].dt.date)["user_id"].nunique()

print(dau)

date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [40]:
avg_dau = dau.mean()
print(avg_dau)

560.4666666666667

In [41]:
df["date"] = pd.to_datetime(df["date"])

first_visit = df.groupby("user_id")["date"].min().reset_index()
first_visit.columns = ["user_id", "first_date"]

cohort = first_visit[first_visit["first_date"] == "2023-11-01"]["user_id"]

returned = df[
    (df["user_id"].isin(cohort)) & 
    (df["date"] == "2023-11-02")
]["user_id"].nunique()

cohort_size = cohort.nunique()

retention_d1 = returned / cohort_size

print(retention_d1)

0.2664526484751204

In [42]:
df["date"] = pd.to_datetime(df["date"])

november = df[
    (df["date"] >= "2023-11-01") &
    (df["date"] < "2023-12-01")
]

In [43]:
users_with_views = november[
    november["view_adverts"] > 0
]["user_id"].nunique()

In [44]:
total_users = november["user_id"].nunique()

In [45]:
conversion = users_with_views / total_users
print(conversion)

0.4631496269145176

In [46]:
df["date"] = pd.to_datetime(df["date"])

df_nov = df[df["date"].dt.month == 11]
avg_views = df_nov.groupby("user_id")["view_adverts"].sum().mean()
avg_views

np.float64(2.8687000916350307)

In [47]:
df = pd.read_csv('AB_test.csv')
results = []

for exp in df['experiment_num'].unique(): data = df[df['experiment_num'] == exp]
    
group_A = data[data['experiment_group'] == 'control']['revenue'].dropna()
group_B = data[data['experiment_group'] == 'test']['revenue'].dropna()
    
arpu_A = group_A.mean()
arpu_B = group_B.mean()
    
t_stat, p_value = stats.ttest_ind(group_A, group_B, equal_var=False)
    
results.append({'experiment': exp,'ARPU_control': arpu_A,'ARPU_test': arpu_B,'p_value': p_value})

pd.DataFrame(results)

   experiment  ARPU_control  ARPU_test   p_value
0           3    663.206452  998.66875  0.060315

In [48]:
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [49]:
df = pd.read_csv('Lister.csv')

In [50]:
df.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [51]:
arpu = df.groupby('user_id')['revenue'].sum().mean()
print(arpu)

156.48387096774192

In [52]:
median_age = df.groupby('user_id')['age'].first().median()
print(median_age)

28.0